import { StyleSheet } from "react-native";

export const MARGIN = 10;
const FONT_FAMILY = "Inter";

export const palette = {
  primary: "#FF9FC9",
  secondary: "#FFCAE1",
  contrast: "#848484",
  accent: "#CACACA",
  border: "#f1abc6",
  white: "#ffffff",
  black: "#000000",
  text: "#000000",
};

export default StyleSheet.create({
  header: {
    marginTop: -28,
    fontSize: 22,
    fontFamily: FONT_FAMILY,
    color: palette.text,
    textAlign: "center",
  },

  headerUnderline: {
    backgroundColor: "#000000",
    width: 40,
    height: 4,
    margin: "auto",
    borderRadius: 60,
    marginTop: 5,
  },

  list: {
    marginTop: 4,
    borderTopWidth: 4,
    borderBottomWidth: 4,
    marginBottom: 4,
    borderColor: palette.border,
    backgroundColor: palette.primary,
    flex: 1,
  },
  app: {
    marginTop: 50,
    flex: 1,
  },
  prompt: {
    margin: MARGIN * 4,
    alignSelf: "stretch",
    borderWidth: 2,
    borderRadius: 12,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderColor: palette.border,
    backgroundColor: palette.primary,
  },
  promptText: {
    margin: MARGIN,
    fontSize: 20,
    fontFamily: FONT_FAMILY,
    color: palette.text,
    textAlign: "center",
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "center",
  },
  button: {
    margin: MARGIN,
    borderRadius: 36,
    color: palette.text,
    borderColor: palette.border,
    backgroundColor: palette.black,
    padding: 10,
    alignItems: "center",
  },
  buttonText: {
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: FONT_FAMILY,
    color: palette.white,
    textAlign: "center",
  },
  buttonPressed: {
    margin: MARGIN,
    marginTop: MARGIN + 2,
    borderWidth: 1,
    backgroundColor: palette.primary,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderRadius: 12,
    borderColor: palette.border,
    padding: 10,
    alignItems: "center",
    fontFamily: FONT_FAMILY,
  },
  listItem: {
    margin: MARGIN,
    borderWidth: 2,
    borderRadius: 12,
    fontFamily: FONT_FAMILY,
    borderColor: palette.border,
    padding: 10,
  },
  listItemText: {
    fontSize: 24,
    fontFamily: FONT_FAMILY,
    color: palette.text,
  },
  matchList: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 8,
    marginTop: 10,
  },
  matchListContent: {
    paddingBottom: 20,
  },
  matchCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 2,
    borderColor: "#cacaca19",
    borderRadius: 20,
    padding: 2,
    marginBottom: 6,
  },
  profileButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: palette.accent,
    borderWidth: 2,
    borderColor: palette.border,
    padding: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  matchInfo: {
    flex: 1,
    marginHorizontal: 6,
    justifyContent: "center",
  },
  matchName: {
    fontSize: 18,
    fontFamily: FONT_FAMILY,
    fontWeight: "bold",
    color: palette.text,
    marginBottom: 6,
  },
  matchStripBox: {
    height: 12,
    borderRadius: 8,
    backgroundColor: palette.accent,
    width: "100%",
    elevation: 6,
    shadowColor: "rgb(1, 1, 1)",
  },
  matchStrip: {
    height: 12,
    borderRadius: 8,
    backgroundColor: palette.primary,
    width: "100%",
  },
  contactButton: {
    minWidth: 72,
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderRadius: 28,
  },
  contactButtonText: {
    fontSize: 14,
    fontWeight: "bold",
  },
  inputText: {
    margin: MARGIN,
    fontFamily: FONT_FAMILY,
    borderRadius: 36,
    backgroundColor: palette.primary,
    padding: 4,
    paddingHorizontal: 25,
    fontSize: 18,
    color: palette.text,
  },
  inputDate: {
    margin: MARGIN,
    fontFamily: FONT_FAMILY,
    borderRadius: 36,
    backgroundColor: palette.primary,
    padding: 4,
    paddingHorizontal: 20,
    fontSize: 18,
    color: palette.text,
  },
  inputTextTitle: {
    marginLeft: 35,
    fontSize: 18,
    fontWeight: "bold",
  },
  dropDownInput: {
    margin: MARGIN,
    marginTop: 0,
    fontFamily: FONT_FAMILY,
    borderRadius: 36,
    backgroundColor: palette.primary,
    padding: 4,
    paddingHorizontal: 25,
    color: palette.text,
  },
  dropdownOpenContainer: {
    zIndex: 1,
    elevation: 1,
  },
  dropdownContainer: {
    position: "relative",
  },
  dropdownMenu: {
    backgroundColor: palette.secondary,
    borderRadius: 12,
    paddingVertical: 6,
    marginHorizontal: 10,
  },
  dropdownOption: {
    paddingVertical: 10,
    paddingHorizontal: 25,
  },
  profilePicture: {
    width: 160,
    height: 160,
    backgroundColor: palette.accent,
    borderRadius: 160 / 2,
    overflow: "hidden",
  },
  icon: {
    color: palette.text,
  },
});
