import { StyleSheet } from "react-native";

export const MARGIN = 10;
const FONT_FAMILY = "Inter";

export const palette = {
  primary: "#FF9FC9",
  secondary: "#FFCAE1",
  contrast: "#848484",
  accent: "#CACACA",
  border: "#f1abc6",
  white: "#ffffff",
  black: "#000000",
  text: "#000000",
};

export default StyleSheet.create({
  header: {
    marginTop: -28,
    fontSize: 22,
    fontFamily: FONT_FAMILY,
    color: palette.text,
    textAlign: "center",
  },

  headerUnderline: {
    backgroundColor: "#000000",
    width: 40,
    height: 4,
    margin: "auto",
    borderRadius: 60,
    marginTop: 5,
  },

  list: {
    marginTop: 4,
    borderTopWidth: 4,
    borderBottomWidth: 4,
    marginBottom: 4,
    borderColor: palette.border,
    backgroundColor: palette.primary,
    flex: 1,
  },
  app: {
    marginTop: 50,
    flex: 1,
  },
  prompt: {
    margin: MARGIN * 4,
    alignSelf: "stretch",
    borderWidth: 2,
    borderRadius: 12,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderColor: palette.border,
    backgroundColor: palette.primary,
  },
  promptText: {
    margin: MARGIN,
    fontSize: 20,
    fontFamily: FONT_FAMILY,
    color: palette.text,
    textAlign: "center",
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "center",
  },
  button: {
    margin: MARGIN,
    borderRadius: 36,
    color: palette.text,
    borderColor: palette.border,
    backgroundColor: palette.black,
    padding: 10,
    alignItems: "center",
  },
  buttonText: {
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: FONT_FAMILY,
    color: palette.white,
    textAlign: "center",
  },
  buttonPressed: {
    margin: MARGIN,
    marginTop: MARGIN + 2,
    borderWidth: 1,
    backgroundColor: palette.contrast,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderRadius: 12,
    borderColor: palette.accent,
    padding: 10,
    alignItems: "center",
    fontFamily: FONT_FAMILY,
  },
  listItem: {
    margin: MARGIN,
    borderWidth: 2,
    borderRadius: 12,
    fontFamily: FONT_FAMILY,
    borderColor: palette.border,
    padding: 10,
  },
  listItemText: {
    fontSize: 24,
    fontFamily: FONT_FAMILY,
    color: palette.text,
  },
  matchList: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 8,
    marginTop: 10,
  },
  matchListContent: {
    paddingBottom: 20,
  },
  matchCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 2,
    borderColor: "#cacaca19",
    borderRadius: 20,
    padding: 2,
    marginBottom: 6,
  },
  profileButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: palette.accent,
    padding: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  matchInfo: {
    flex: 1,
    marginHorizontal: 6,
    justifyContent: "center",
  },
  matchName: {
    fontSize: 18,
    fontFamily: FONT_FAMILY,
    fontWeight: "bold",
    color: palette.text,
    marginBottom: 6,
  },
  matchStripBox: {
    width: "100%",
    backgroundColor: "#E8E8E8",
    borderRadius: 12,
    padding: 4,
    marginBottom: 14,
  },
  matchStrip: {
    height: 16,
    borderRadius: 12,
    backgroundColor: palette.primary,
    width: "100%",
  },
  profileInfo: {
    width: "100%",
    marginTop: 20,
    alignItems: "flex-start",
    paddingHorizontal: 20,
  },
  profileName: {
    fontSize: 28,
    fontFamily: FONT_FAMILY,
    fontWeight: "800",
    color: palette.text,
    marginBottom: 6,
  },
  profileInfoText: {
    fontSize: 16,
    fontFamily: FONT_FAMILY,
    color: palette.text,
    marginBottom: 6,
    textAlign: "left",
  },
  profileMeta: {
    fontSize: 14,
    fontFamily: FONT_FAMILY,
    color: palette.contrast,
    marginBottom: 16,
    textAlign: "left",
  },
  interests: {
    width: "100%",
    marginTop: 20,
    alignItems: "flex-start",
    paddingHorizontal: 20,
  },
  interestsHeader: {
    fontSize: 18,
    fontFamily: FONT_FAMILY,
    fontWeight: "bold",
    color: palette.text,
    marginBottom: 10,
    textAlign: "left",
  },
  interestItem: {
    width: "100%",
    backgroundColor: palette.secondary,
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  interestText: {
    fontSize: 14,
    fontFamily: FONT_FAMILY,
    color: palette.text,
    textAlign: "center",
  },
  modalContent: {
    width: "90%",
    maxWidth: 420,
    alignItems: "center",
    paddingTop: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: FONT_FAMILY,
    fontWeight: "bold",
    color: palette.text,
    marginBottom: 8,
  },
  modalHeaderUnderline: {
    width: 60,
    height: 4,
    backgroundColor: palette.text,
    borderRadius: 4,
    marginBottom: 24,
  },
  matchScoreText: {
    fontSize: 16,
    fontFamily: FONT_FAMILY,
    color: palette.text,
    marginBottom: 12,
  },
  matchScoreBar: {
    width: "100%",
    backgroundColor: "#E8E8E8",
    borderRadius: 12,
    padding: 4,
    marginBottom: 24,
  },

  contactButton: {
    minWidth: 72,
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderRadius: 28,
  },
  contactButtonText: {
    fontSize: 14,
    fontWeight: "bold",
  },
  inputText: {
    margin: MARGIN,
    fontFamily: FONT_FAMILY,
    borderRadius: 36,
    backgroundColor: palette.primary,
    padding: 4,
    paddingHorizontal: 25,
    fontSize: 18,
    color: palette.text,
  },
  inputDate: {
    margin: MARGIN,
    fontFamily: FONT_FAMILY,
    borderRadius: 36,
    backgroundColor: palette.primary,
    padding: 4,
    paddingHorizontal: 20,
    fontSize: 18,
    color: palette.text,
  },
  inputTextTitle: {
    marginLeft: 35,
    fontSize: 18,
    fontWeight: "bold",
  },
  dropDownInput: {
    margin: MARGIN,
    marginTop: 0,
    fontFamily: FONT_FAMILY,
    borderRadius: 36,
    backgroundColor: palette.primary,
    padding: 4,
    paddingHorizontal: 25,
    color: palette.text,
  },
  dropdownOpenContainer: {
    zIndex: 1,
    elevation: 1,
  },
  dropdownContainer: {
    position: "relative",
  },
  dropdownMenu: {
    backgroundColor: palette.secondary,
    borderRadius: 12,
    paddingVertical: 6,
    marginHorizontal: 10,
  },
  dropdownOption: {
    paddingVertical: 10,
    paddingHorizontal: 25,
  },
  profilePicture: {
    width: 160,
    height: 160,
    backgroundColor: palette.accent,
    borderRadius: 160 / 2,
    overflow: "hidden",
  },
  icon: {
    color: palette.text,
  },
  skeletonProfile: {
    width: 64,
    height: 64,
    borderRadius: 29,
    backgroundColor: palette.accent,
  },
  skeletonName: {
    height: 24,
    borderRadius: 4,
    backgroundColor: palette.accent,
    marginBottom: 10,
    width: "70%",
  },
  skeletonStrip: {
    height: 12,
    borderRadius: 8,
    backgroundColor: palette.accent,
    width: "100%",
  },
  skeletonButton: {
    minWidth: 72,
    height: 38,
    borderRadius: 28,
    backgroundColor: palette.accent,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: palette.white,
    paddingTop: 30,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  closeButton: {
    position: "absolute",
    top: 20,
    right: 20,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: palette.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  modalPicture: {
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: "#fdfd",
    marginBottom: 24,
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    padding: 10,
    marginBottom: 10,
    backgroundColor: palette.secondary,
    borderRadius: 10,
  },
  contactText: {
    fontSize: 16,
    fontFamily: FONT_FAMILY,
    color: palette.text,
    flex: 1,
  },
  // ----------------- Login -----------------------
  loginSafeArea: {
    flex: 1,
  },
  loginContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  loginAppName: {
    fontSize: 30,
    fontWeight: "bold",
    fontFamily: "Inter",
    color: "#000000",
    marginBottom: 82,
    letterSpacing: 0.5,
  },
  loginSubheading: {
    fontSize: 14,
    fontFamily: "Inter",
    color: palette.text,
    textAlign: "center",
    marginBottom: 20,
    opacity: 0.85,
    lineHeight: 20,
  },
  loginInput: {
    width: "100%",
    height: 52,
    backgroundColor: palette.primary,
    borderWidth: 2,
    borderRadius: 12,
    borderColor: palette.border,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    paddingHorizontal: 16,
    fontSize: 16,
    fontFamily: "Inter",
    color: palette.contrast,
    marginBottom: 14,
  },
  loginContinueBtn: {
    width: "100%",
    height: 52,
    backgroundColor: "#1a1a1a",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#000",
    borderBottomWidth: 4,
    borderRightWidth: 4,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  loginContinueBtnText: {
    color: "#fff",
    fontSize: 18,
    fontFamily: "Inter",
  },
  signUpButton: {
    color: "#000",
    fontWeight: "bold",
  },
  loginBtnPressed: {
    borderBottomWidth: 2,
    borderRightWidth: 2,
    opacity: 0.9,
  },
  loginConfirmation: {
    marginTop: 14,
    fontSize: 13,
    fontFamily: "Inter",
    color: palette.text,
    textAlign: "center",
    opacity: 0.9,
  },
});
